---
title: "Documentation fonctionnelle"
author: "Evan Lane et Tom Baudry"
output: html_document
---

**Présentation de l'application**

Dans cette documentation fonctionnelle, nous vous présenterons les différentes options que l'application propose, ce qui la compose et comment les utiliser.

Pour commencer, l'application est composée de 4 onglets :

  - L'onglet "Comparaison territoire", qui présente 2 graphiques sur les différents type de logements, donc maison ou appartement, réparti par surface habitable. Cela permet de voir le parc immobilier des 2 départements et faire des liens par la suite avec les note de DPE.
  
  - L'onglet "Carte avec clustering", qui montre une carte intéractive sur l'emplacement géographique des logements en Savoie et Haute-Savoie. Elle permet de cibler géographiquement une zone et aussi de voir la répartition des logements sur le territoire, notamment pour en savoir plus sur l'environnement naturel (montagne, lac, ville,...). Il y a une possibilité de filtrer sur les différentes classes de DPE avec des coches (A à G).
  
  - L'onglet "Analyse DPE", qui va présenter les différents axes d'études des DPE entre les 2 départements, avec des graphiques divers. C'est le coeur de l'étude statistique qu va permettre d'observer les différences et ressemblences entre ces départements frontaliers au niveau des DPE. Il y a la possibilité de filtrer sur la superficie du logement avec une échelle graduée (de 0 à 500 m²).
  
  - L'onglet "Contexte", qui va présenter les données utilisées pour l'étude, avec leur signification, tout cela résumé dans un tableau.
   
Tous ces onglets sont filtrables sur les départements (Savoie et Haute-Savoie), selon le code postal (73100 par exemple) mais aussi selon le type du logement (neuf ou ancien). On peut donc passer d'onglet en onglet en cliquant sur le nom de celui-ci puis filtrer les graphiques que l'on veut sur chacun des onglets. L'ensemble des filtres décrits précédement son situés dans la barre latérale à gauche de l'application.

De plus, un filtre de thème est présent en haut à gauche de la barre latérale, au dessus du logo ENEDIS. Il permet de changer le thème général de l'application avec 5 variantes différentes (Cosmo, Darkly, Lumen, Superhero et Minty).